IBM-Cloud/gp-js-client

test/client-test.js
test/lib/gp-test.js

* Updated test script for uploading resource strings with a language ID not supported by MT. Also added a test case for uploading strings with an invalid language ID.
* remove 'es' from default list
* Make source/target langs parameterized.
* verify both value and sourceValue
Author:    Yoshito Umaoka <yoshito_umaoka@us.ibm.com>
Author:    Steven R. Loomis <srloomis@us.ibm.com>
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/22

Update to GP capability

---

lib/client.js
test/client-test.js

As the bug noted, bundle.getBundleInfo should work as an alias for bundle.getInfo
No doc impact as this is not the preferred function name.
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/26

add bundle.getBundleInfo alias

---

README.md
template-README.md

NB it's also documented in TESTING.md
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/25

doc: document local-credentials.json

---

package.json
template-README.md

* bump jsdoc-to-markdown to 2.0.1 (was broken)
* fix missed stuff in the template

doc: bump dependency, regen doc

---

lib/client.js
test/client-test.js

* cause entry/bundle/user getInfo to return an empty ({}) metadata instead of null
FIxes: https://github.com/IBM-Bluemix/gp-js-client/issues/50

re-enable and fix metadata test

---

README.md
lib/client.js
package.json
template-README.md
test/client-test.js

* add some tests for functions that were missed
* update Bundle.updateStrings to take a languageId (which was broken - oops)
* fix code coverage output
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/47

Update code coverage to 100% functions

---

test/client-test.js

* REST server now returns item sequence number on source resource entry
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/58

Fix metadata test breakage

---

lib/client.js
test/client-test.js
test/rest-test.js

* improve consistency with other clients.
* historical note:  /rest used to be NOT included in the URL from the GP broker.
(this was in the Experimental version- so a very old change.)
* this affects internal URL usage, and the INTERNAL `_getUrl()` function.
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/56

Add /rest instead of dropping it from the URL

---

README.md
lib/client.js
test/client-test.js

* bundle: support in create/update/getInfo
* resourceEntry: support in update/getInfo
* make some setters more future-proof
Remaining:  Not sure if uploadStrings or updateStrings also has notes support.
https://github.com/IBM-Bluemix/gp-js-client/issues/54

Add support for Notes field

---

README.md
package.json
template-README.md

* announce dropping support for node v0.12
* also, add an `engines` field with value `node ≥ 0.12` for now, to be updated later
Supports: https://github.com/IBM-Bluemix/gp-js-client/issues/55

drop v0.12 in v2.0, add "engines" to package.json

---

test/tr-test.js

Improve tests
* hopefully cause a shorter time interval
* fix the test loop

Speedup TR test

---

lib/client.js
lib/utils.js
test/client-test.js

use `defineProperty` to "hide" these properties. This way `console.dir()` or `Object.keys()` is more useful on the top level client object and other generated objects.  Otherwise, there are various circular references and internal contents exposed. Exposed isn't too bad, but it makes the objects ugly to print out.
```
> console.dir(client.bundle('Something'))
Bundle {
id: 'Something',
serviceInstance: 'fefog854b59bc71dbc88eb454f378b8200e354251280' }
> JSON.stringify(client.tr('my-tr-ID'))
'{"id":"my-tr-ID","serviceInstance":"fefog854b59bc71dbc88eb454f378b8200e354251280"}'
```
Note: I _think_ this code should work on v0.12 from docs and my local test, but would be good to make sure travis agrees.  
Fixes #81

"Hide" the .gp and .swaggerClient properties

---

.travis.yml
README.md
package-lock.json
package.json
template-README.md

* bump version to v2.0.0-0
* drop Node v0.12 from travis and package.json
No actual breaking changes here, but get ready.
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/55

Drop support for Node v0.12, begin v2.0

---

.gitignore
package.json

The README.html is a transient file, a pre-rendered version of the README. It should not be included in the npm tarball, as it might be out of date.
README.html is only generated by explicitly calling `npm run html`.
Even though README.html is in `.gitignore`, it is explicitly un-ignored by npm.
- remove README.html in the `prepack` stage
- also ignore the npm tarball in .gitignore
You can test this with `npm run html ; npm pack`. You should see a `g11n-pipeline*.tgz` file that does NOT contain README.html.
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/94

Remove README.html in prepack

---

lib/gp-hmac.js
package-lock.json
package.json

- reset package.json to accept later swagger-client versions
- apply() function needed to return `obj` instead of `true` for the load of swagger.json
This bug was introduced in https://github.com/IBM-Bluemix/gp-js-client/issues/70  because before https://github.com/swagger-api/swagger-js/pull/1161 it seems the requestInterceptor was not called for /swagger.json loads.
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/104

fix HMAC requestInterceptor for Swagger 3.3.x

---

lib/gp-hmac.js
test/client-test.js
test/hmac-test.js

- and unit tests thereof
- also, uncomment the HMAC debugging code (if variable GP_VERBOSE is true)
Fixes: https://github.com/IBM-Cloud/gp-js-client/issues/113

Normalize URLs in HMAC interceptor

---

.eslintrc.js

- we don't really care about the line endings, they will be whatever
works on the host.
Fixes: https://github.com/IBM-Cloud/gp-js-client/issues/109
see https://eslint.org/docs/rules/linebreak-style

disable linebreak-style in eslint

---

API.md
CLI.md
lib/client.js
lib/consts.js
lib/gp-iam.js
lib/gpcli.js
lib/main.js
test/cli-test.js
test/lib/gp-test.js

iam: Phase I: API Key

---

lib/client.js
lib/gp-iam.js
package-lock.json
package.json

followon to #151 
- make internal client.swaggerClient a getter instead of a property.
(original property at _swaggerClient).
All internal clients must go through this getter.
- support IAM token. No API change.
- Internal env vars:
- GP_USE_APIKEY=true to not use tokens,
- IAM_TOKEN_EXPIRY_THRESHOLD_PROP_KEY to change the expiry derating from
0.85 to something else.
Fixes: https://github.com/IBM-Cloud/gp-js-client/issues/150

IAM Support: phase II: token management

---

lib/gp-hmac.js
package-lock.json
package.json

See: https://nodejs.org/api/deprecations.html#deprecations_dep0005_buffer_constructor
The use of `Buffer()` was deprecated, the API used in this PR dates from Node version 5, and we require Node version 8+ for this SDK. So it is a safe replacement.

fix use of deprecated Buffer in hmac

---

.travis.yml
README.md

- cleanup references to old Node versions
- mention #155 and #158 in news
low priority, just to update it for the next publish

doc: update README and .travis.yml

---

API.md
README.md
lib/main.js
test/cli-test.js
test/client-test.js
test/doc-test.js
test/rest-test.js
test/tr-test.js

~Deprecate~ Remove the `getClient()` function that returns a Client object. (Yes, the main API since the beginning of this project!)
Instead, use `connect()` which returns a promise and actually tries to load the swagger.json. Callers are expected to handle any rejections right away.
Fixes: https://github.com/IBM-Cloud/gp-js-client/issues/101

add connect(), deprecate getClient()

---

package.json
test/lib/byscheme.js
test/lib/gp-test.js
test/rest-test.js

- remove last usages of 'request' in favor of 'bent' (which is already a dependency
due to IAM)
- cleanup more async test stuff

request -> bent
