IBM-Cloud/gp-js-client

- README.md
- package.json
- template-README.md
- test/rest-test.js
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/24
> update version to 1.2.0-BETA

- TESTING.md
Document how to do internal testing
https://github.com/IBM-Bluemix/gp-js-client/issues/18
> Internal testing

- .travis.yml
- README.md
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/36
> add a basic .travis.yml and and add to README

- lib/gp-hmac.js
- package.json
- test/client-test.js
> Fix encoding

- .travis.yml
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/39
> use a "fake broker" for travis testing

- README.md
- lib/client.js
- test/client-test.js
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/40
> add a Bundle.languages() convenience function

- .gitignore
- README.md
- lib/client.js
- test/client-test.js
Add assertion to prevent a more confusing message from leaking out
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/35
> verify args in uploadStrings before swagger, add bundle.entries()

- .travis.yml
- README.md
* also cache node_modules and .nvm
* also move fakebroker token into secret
* also update README to point to coverity status
> add coverity scan

- TESTING.md
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/38
just update to what's true
> make TESTING.md more consistent

- .travis.yml
- README.md
- package-lock.json
- package.json
Actually, this PR is just to bump node versions, some dependencies, etc. to reduce thrash when we go to do  #68
> Update some dependencies and versions

- README.md
- lib/client.js
- lib/tr.js
- template-README.md
> Improve docs for HT

- README.md
- lib/tr.js
- test/tr-test.js
support updating TRs.
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/73
> support tr.update()

- README.md
- lib/client.js
- test/client-test.js
* information about the service instance itself
* also document getServiceInfo further
Fixes #66
> add support for getServiceInstanceInfo

- .travis.yml
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/71
> Change code coverage target from node 6 to node 8

- test/tr-test.js
re-enable HPE merge test, oops
Fixes: #87
> test: re-enable HPE merge test

- README.md
- template-README.md
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/93
Docs only, no code change needed.
> document use with browserify

- lib/client.js
- lib/partner.js
- test/partner-test.js
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/96
Note that the tests purposely just test that the function can be called, I don't have a good way to test these at present.
> Initial support for partner APIs

- package-lock.json
- package.json
Workaround for: https://github.com/IBM-Bluemix/gp-js-client/issues/104
> pin swagger version to 3.2.x for now.

- test/client-test.js
- test/data/t1_1_es.json
- test/partner-test.js
- test/tr-test.js
Fixes the tests so they work with internal tests.
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/102
> Fixes for internal API and internal test mode

- lib/partner.js
Fixes: https://github.com/IBM-Bluemix/gp-js-client/issues/99
- note- still not setup to test this well on the fakebroker.
> update partner API

- .gitignore
- README.md
- package.json
- template-README.md
- also .DS_Store
https://github.com/IBM-Cloud/gp-common/issues/18
> IBM Cloud naming

- package-lock.json
- package.json
- doesn't affect swagger
- to fix some warnings about some dependencies
> deps: bump dev dependencies

- .travis.yml
should see the build working again
> remove fakebroker env from .travis.yml

- test/partner-test.js
- not sure how it passed in travis already?
> Adding a "use const" for now so it passes under 4

- package-lock.json
- package.json
- test/client-test.js
- Fixes #121 by improving deps
- also updates tests to match current REST behavior
> Security 3.x

- lib/gp-hmac.js
- package-lock.json
- test/hmac-test.js
> using GP-Date header instead of Date for hmac auth

- API.md
- CLI.md
- README.md
- bin/gp-js-cli
- lib/bundle.js
- lib/client.js
- lib/gpcli-verbs.js
- lib/gpcli.js
- lib/utils.js
- package-lock.json
- package.json
- test/cli-test.js
- test/lint-test.js
- test/util-test.js
> add a CLI to g11n-pipeline

- CLI.md
- lib/gpcli-verbs.js
- lib/gpcli.js
- package-lock.json
- package.json
- test/cli-test.js
- test/data/flattest-expand.json
- test/data/flattest.json
support -T option for flatten/unflatten
Fixes: https://github.com/IBM-Cloud/gp-js-client/issues/133
> un/flatten CLI

- .travis.yml
- test/lib/gp-test.js
- fix test case to match current headers
- also, bump to Node 10 (soon LTS)
Fixes: #142
> Fix CORS test yet again, bump to Node 10

- lib/client.js
- lib/htmldoc.js
- lib/mddoc.js
- package-lock.json
- package.json
Replacing operation ids for document apis based on new swagger definition.  Need to update the broker instance for the build to succeed
> updated operationIds for doc apis

- test/rest-test.js
Fixes: https://github.com/IBM-Cloud/gp-js-client/issues/148
> For HTTPS, allow redirect to (403) as well as 301 error

- package-lock.json
- package.json
> deps: security fixes

- test/client-test.js
- test/doc-test.js
- test/rest-test.js
> Misc test fixes

- lib/client.js
- lib/doctr.js
- lib/gpcli-verbs.js
- lib/tr.js
- test/client-test.js
- test/tr-test.js
Support for implementing tr api changes
- asynchronous TR submission
- summary view of draft TRs
> tr api changes

- package.json
- test/client-test.js
Fixes: https://github.com/IBM-Cloud/gp-js-client/issues/169
also fix some  deps issues:
- working around https://github.com/mikeal/bent/issues/49
- removing `minimist` (it should only be included in the cli)
- removing `istanbul` (it's obsolete)
> Retry the first connection to the server up to a minute

- package.json
- Update to da17807d1453bc8e2aca728b181bebc340ad282b (#170)
- bent@1.6 has been published, fixing https://github.com/mikeal/bent/issues/49
> deps: update bent@1.6
